before:
  hooks:
    - go mod tidy

builds:
- id: cmd-ai-resolver
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -X 'github.com/witalisoft/cmd-ai-resolver/cmd.Version={{.Version}}'

archives:
- ids:
  - cmd-ai-resolver

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
